KVStore:
    internal_host: localhost
    host: localhost
    port: 50123 
masterNode:
    internal_host: localhost
    host: localhost
    port: 50124
wordCountClinet:
    inputFile: textFiles/book2.txt
    outputfile: output/wordCountOutput.txt
invIndexClinet:
    inputDir: textFiles
    outputfile: output/invIndexOutput.txt
