START_KVSTORE:
	python3 KVStore/KVServer.py

START_MR_MASTERNODE:
	python3 mapReduceMasterNode.py

START_WC_CLIENT:
	python3 wordCountClient.py

START_INV_IDX_CLIENT:
	python3 inverseIndexClient.py
